### PR TITLE
Warren's Formatting Branch

### PR DESCRIPTION
**Pull request by gracebilliris**
> WIP

### CODE REVIEW

**Comment by bluebluefrog** [comment]
All models looks good

**Comment by bluebluefrog** [comment]
No changes made in code standards were upheld

**Review by Yeran-H — CHANGES_REQUESTED** [review]
Found inconsistencies in the code against the coding standards. @bluebluefrog

**Review by bluebluefrog — APPROVED** [review]

**Review by Ashish-Chadha — APPROVED** [review]
Formatting done to the files looks good!

**Review by Yeran-H — APPROVED** [review]
Formating changes look good

**Pull request merged**
